### PR TITLE
Add `waiting` status to CheckRunState

### PR DESCRIPTION
**Pull request by Fs00**
Needed to fix slapperwan/gh4a#1169.
~~I suspect this may be the status in which the message "Waiting for status to be reported" is being displayed for a check run.~~

### CODE REVIEW

**Comment by Fs00** [comment]
@maniac103 You can release a new version of the bindings when you have time, or re-release 0.7.0.6 with this change [since that release didn't quite work](https://github.com/slapperwan/gh4a/pull/1157#issuecomment-1000470388) :)

**Comment by maniac103** [comment]
Done, but 0.7.0.7 doesn't work any better. [The build log](https://jitpack.io/com/github/maniac103/githubsdk/0.7.0.7/build.log) shows gradle can't find any tasks, but on my local PC the same command works totally fine...

**Comment by maniac103** [comment]
[This](https://github.com/maniac103/GitHubSdk/commit/9af50e301416c05e3a3b6cc4b47d63546ac3fbf4) seems to have done it; got the hint from [here](https://stackoverflow.com/questions/67599438/gradle-7-and-jitpack-io-runs-into-error-during-publish).

**Comment by Fs00** [comment]
For posterity, this is how the check run waiting state looks in GitHub web UI:

waiting_check

**Pull request merged**
