### PR TITLE
Add some miscellaneous missing fields

### PR DESCRIPTION
**Pull request by Fs00**
This PR adds the following missing fields:
- `has_discussions`/`has_projects` to repositories
- `status_reason` to IssueRequest, to allow specifying a reason when closing an issue
- `subject_type` to review comments, to be able to determine when a review comment was added to a specific line or to the whole file (see [this GH changelog post](https://github.blog/changelog/2023-04-11-commenting-on-files-in-a-pull-request-is-now-generally-available/) for more details)

I've also changed the type of SearchPage `total_count` field from int to long. This should likely fix slapperwan/gh4a#1277.

Once this is merged, feel free to release a new version of the library. Thanks!

### CODE REVIEW

**Comment by Fs00** [comment]
Hello @maniac103, is OctoDroid development just on hold for the time being or has it been stopped for good?
I'm asking because the app seems to have been removed from the Play Store and there has been no activity on the repository since May.
I'd like to make a few more contributions, but I won't start working on them if there aren't going to be any more releases.

**Comment by maniac103** [comment]
> is OctoDroid development just on hold for the time being or has it been stopped for good?

I really don't *want* to stop development on it, it's just that I severely lack time due to RL constraints (work, family etc.).

> I'm asking because the app seems to have been removed from the Play Store and there has been no activity on the repository since May.

I wasn't even aware it was removed from Play Store - ouch :-(
I quickly checked, and it seems it was removed because they supposedly couldn't review due to the lack of a testing account. They sent this screenshot:

grafik

with this description: `You didn’t provide an active demo/guest account or a valid username and password which we need to access your app.`

OTOH, I can't think of a good way to fix that issue, except creating an account on our behalf?

>  I'd like to make a few more contributions, but I won't start working on them if there aren't going to be any more releases.

I'll gladly add you as member to the repositories, so you can commit changes yourself. I'll also gladly upload APKs to the Play Store, if doing that doesn't involve siginificant amounts of time on my side ;-) First, we'd need to figure out the above issue, though.

**Comment by Fs00** [comment]
I admit I have no knowledge about Play Store policies and testing requirements, but Google response really baffles me.
Why do they require a test account now and previously they didn't? And also, shouldn't the "guest" access without a user be enough for them? It already provides access to the vast majority of the app's features.
We could always provide them a test GitHub account, but at that point the whole situation becomes ridiculous... GitHub is a public platform, why don't they create an account by themselves? 🙃

> I'll gladly add you as member to the repositories, so you can commit changes yourself.

That'd be great to speed some things up, however I don't see myself "maintaining" the app (preparing releases, reviewing PRs, replying to issues etc.) as my time budget is limited too. My contributions would probably be somewhat more frequent, but I don't intend to increase my involvement in the project significantly.
Hope this is fine for you 🙂

**Comment by jimbminor** [comment]
That's fine please do,
 sorry I haven't responded sooner but I've been really busy these last 7
weeks trying to get some projects squared away

**Comment by Fs00** [comment]
Hello @maniac103, are there any news on this?
Have you tried telling Google reviewers that there's no need for a guest account, since the app provides guest access to GitHub without logging in?

**Pull request merged**
