### PR TITLE
Dependency updates and support for comments in timeline API

### PR DESCRIPTION
**Pull request by Fs00**
This PR includes some small additions and adjustments to enable further improvements in the app (I'd recommend to review it commit-by-commit):
- updated dependencies and removed OkHttp logging interceptor. Since the app uses its own interceptor, we can avoid declaring that dependency both in the app and here.
Note that updating Gradle/AGP required me to use the [new syntax for Maven publishing](https://developer.android.com/build/publish-library/configure-pub-variants#understanding-pub-vars) (I'm not 100% sure I got it right, but it looks like it's working) and I had to remove all the code related to the publishing plugin used upstream (the plugin could not be fetched anymore due to JCenter being shut down).
- added missing fields used by [`commented` events in timeline API](https://docs.github.com/en/rest/using-the-rest-api/issue-event-types?apiVersion=2022-11-28#commented). This will allow us to avoid calling the issue comments API in the app and use the timeline API for both comments and events.
Since comment fields are spread on event objects in timeline API, I initially thought to make `IssueEvent` extend `GitHubCommentBase`, but then changed my mind when I noticed that I would've had to create a builder for `IssueEvent` so that the app could clone them to update the reactions.
Instead, I've added the missing comment fields directly on `IssueEvent`, together with a method that allows creating a `GitHubComment` from the event. This way, integrating with existing app logic is easier and there is no need to create a huge builder for IssueEvent.
- last but not least, I have added a convenience `withReactions` method to the `GitHubCommentBase` class hierarchy which will allow to avoid some - admittedly inelegant - downcasts in the app when cloning comments to update their reactions, [as the AutoValue documentation recommends for those use-cases](https://github.com/google/auto/blob/main/value/userguide/builders-howto.md#-include-with--methods-on-my-value-class-for-creating-slightly-altered-instances).
- _update (11/10):_ I've added a couple of undocumented issue event types I've found in the wild that are related to the [merge queue feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue) (you can see them in [this API response](https://api.github.com/repos/servo/servo/issues/33798/timeline))

Could you release a new version of the library when this is merged?

### CODE REVIEW

**Comment by Fs00** [comment]
@maniac103 Have you had a chance to look into this? Is there anything you'd like to discuss before merging?

**Comment by maniac103** [comment]
Nope, I just totally missed it :-(

**Comment by Fs00** [comment]
Thank you! Have you already tried to publish a new release of the library with these changes?

(btw, can we reconsider merging these bindings in the app repo? Upstream can be considered dead nowadays, managing this library as a separate package seems overkill at this point IMO)

**Comment by maniac103** [comment]
> Have you already tried to publish a new release of the library with these changes?

No, weren't near a Linux PC yesterday. I've tagged 0.7.0.16 now.

> btw, can we reconsider merging these bindings in the app repo? Upstream can be considered dead nowadays, managing this library as a separate package seems overkill at this point IMO

I don't really care either way, as long as I don't have much work with it ;-)

**Comment by Fs00** [comment]
Sorry for bothering you again, but it seems that [the JitPack build failed](https://jitpack.io/com/github/maniac103/githubsdk/0.7.0.16/build.log) due to JDK 8 being used for the build ([which turns out to be the default on JitPack](https://jitpack.io/docs/BUILDING/#java-version)) instead of JDK 11, which is the minimum required by AGP. For some unknown reason, previous builds were correctly using JDK 11 as far as I can see (like [this one](https://jitpack.io/com/github/maniac103/githubsdk/0.7.0.14/build.log)).

But what's weird is that when I was looking into the build logs, the build for the previous version (0.7.0.15) [somehow restarted and failed](https://jitpack.io/com/github/maniac103/githubsdk/0.7.0.15/build.log) because the publishing plugin used upstream could not be fetched anymore on JCenter. So the 0.7.0.15 package got literally yanked... :(

The solution to make JitPack use JDK 11 [seems to be fairly easy](https://stackoverflow.com/a/69281539). However I'd be happier if you could look into integrating the bindings into the app repository when you have some time to avoid this kind of problems in the future...

**Pull request merged**
