### PR TITLE
Increase robustness in case of unknown enum values

### PR DESCRIPTION
**Pull request by Fs00**
In this PR, I've added some missing values for `NotificationReason` enum taken from [here](https://docs.github.com/en/rest/reference/activity#notifications), [here](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#filtering-email-notifications) and slapperwan/gh4a#1117.

But more importantly, I have implemented a solution that prevents the app from crashing when the API returns unknown values for `IssueEventType` and `NotificationReason` enums using Moshi's [EnumJsonAdapter](https://square.github.io/moshi/1.x/moshi-adapters/adapters/com.squareup.moshi.adapters/-enum-json-adapter/index.html).
For now only those two enums are "fault-tolerant", we can always add more later if we want to.

### CODE REVIEW

**Comment by maniac103** [comment]
> But more importantly, I have implemented a solution that prevents the app from crashing when the API returns unknown values for IssueEventType and NotificationReason enums using Moshi's EnumJsonAdapter.

The one potential issue I see with this approach is: how will we know about new enum values (we might want to use some of them) after implementing this?

**Comment by Fs00** [comment]
This is a good point.
The ideal solution would be to log a warning when the null fallback is used, but it isn't possible.

Probably the real question is: do we really care about _all new enum values_? NotificationReason for example is never used in OctoDroid, and many of the issue event types are not worthy of attention.
In the latter case, I think that the "driver" for adding new enum values should not be the app crashing, but the desire of showing new types of events in the app e.g. after seeing them on the web UI.

**Comment by maniac103** [comment]
> I think that the "driver" for adding new enum values should not be the app crashing

That's of course a good point as well ;-) Merging.

**Comment by maniac103** [comment]
Tagged as 0.7.0.4.

**Pull request merged**
