### PR TITLE
Add missing page query parameter to getReviewComments

### PR DESCRIPTION
**Pull request by Fs00**
The `page` parameter was missing, causing the inability to fetch all comments for reviews with more than 30 comments (in OctoDroid this was causing an infinite loop of requests to the first page).

A sidenote: have you ever considered putting this SDK as a Gradle subproject in OctoDroid repo? It would easier to contribute to it (no double PRs needed) and it would spare you the need to release a new version of the library every time :)

### CODE REVIEW

**Comment by Fs00** [comment]
@maniac103 Can we have this fix included before the next release?
(btw, the infinite loop of requests caused by this issue can be seen in https://github.com/TeamNewPipe/NewPipeExtractor/pull/810#pullrequestreview-907684581)

**Comment by maniac103** [comment]
I just created a 0.7.0.9 tag.

**Comment by maniac103** [comment]
> A sidenote: have you ever considered putting this SDK as a Gradle subproject in OctoDroid repo? It would easier to contribute to it (no double PRs needed) and it would spare you the need to release a new version of the library every time :)

I wanted to keep the possibility to do upstream PRs, which isn't possible when importing the project into OctoDroid.

**Comment by Fs00** [comment]
> I just created a 0.7.0.9 tag.

Thanks. Would you mind updating OctoDroid to use the new version of the bindings? I'm not at home these days so I'm limited in what I can do.
If you have some time, I think that before releasing a new version of the app it might be worth looking into slapperwan/gh4a#1179, which is quite a severe issue that requires changes to the bindings.

> I wanted to keep the possibility to do upstream PRs, which isn't possible when importing the project into OctoDroid.

Makes sense, but I'm wondering if this possibility is still relevant given that the upstream project seems to be dead...

**Comment by maniac103** [comment]
> Would you mind updating OctoDroid to use the new version of the bindings? I'm not at home these days so I'm limited in what I can do.

I just tried, but it looks like #13 was incomplete because the returned binary is interpreted as JSON now, which fails. I guess we'll need a `Converter.Factory` for `byte[]` data, similar to `StringResponseConverterFactory`.

**Comment by Fs00** [comment]
I've seen that you added the missing converter factory, thanks! I wasn't aware of that requirement.

**Comment by maniac103** [comment]
I'm not yet sure it'll work though, needs more investigation.

**Pull request merged**
